package com.andrewsenin.pierogi.io;

public enum ErrorType {
    UNTERMINATED_STRING,
    UNRECOGNIZED_CHARACTER,
    UNMATCHED_PARENTHESIS,
    UNEXPECTED_TOKEN,
    INCOMPATIBLE_TYPES,
    MISSING_IDENTIFIER,
    UNDEFINED_SYMBOL,
    DIVISION_BY_ZERO,
    UNCALLABLE_SYMBOL,
    TOO_FEW_ARGUMENTS,
    UNKNOWN_ESCAPE_SEQUENCE,
    TRAILING_ESCAPE
}
