package com.andrewsenin.pierogi.io;

public enum ErrorType {
    UNTERMINATED_STRING,
    UNRECOGNIZED_CHARACTER,
    UNMATCHED_PARENTHESIS,
    UNEXPECTED_TOKEN,
    INCOMPATIBLE_TYPES,
    MISSING_IDENTIFIER,
    UNDEFINED_SYMBOL,
    DIVISION_BY_ZERO,
    UNCALLABLE_VALUE,
    INCORRECT_NUMBER_OF_ARGUMENTS,
    UNKNOWN_ESCAPE_SEQUENCE,
    TRAILING_ESCAPE,
    BUILTIN_FUNCTION_CONTRACT_VIOLATION
}
