package com.andrewsenin.pierogi.io;

public enum ErrorType {
    UNTERMINATED_STRING,
    UNRECOGNIZED_CHARACTER,
    UNMATCHED_PARENTHESIS,
    UNEXPECTED_TOKEN,
    INCOMPATIBLE_TYPES,
    MISSING_IDENTIFIER,
    UNDEFINED_SYMBOL
}
